### ISSUE TITLE
Generated terraform provider for dashboards

### ISSUE THREAD

**Issue by frossano-grafana** [grafana/terraform-provider-schemas#19]
Generated terraform provider for dashboards
This Epic is to create a new, separate provider for dashboard, to work in combination with the existing one, to make it easier to manage dashboards as code in Terraform.
The outcome of the completed tasks is to have an Experimental version ready to give to users
 

```[tasklist]
### List of issues
- [ ] https://github.com/grafana/terraform-provider-schemas/issues/18
- [ ] https://github.com/grafana/terraform-provider-schemas/issues/8
- [ ] https://github.com/grafana/terraform-provider-schemas/issues/11
- [ ] https://github.com/grafana/terraform-provider-schemas/issues/10
- [ ] https://github.com/grafana/terraform-provider-schemas/issues/9
- [ ] https://github.com/grafana/terraform-provider-schemas/issues/16
```
